final feedVehicles = [
  {
    "id": "AFL53G",
    "brandVehicle": "SUZUKI",
    "cardBody": "SIN CARROCERIA",
    "chassisNumber": "9FSNE43P5PC100159",
    "cityRegistration": "STRIA MCPAL TTOyTTE GALAPA",
    "color": "NEGRO",
    "countryRegistration": "Colombia",
    "displacement": "113",
    "engineNumber": "E467-D2R45081",
    "initialRegistrationDate": "2022-03-31T00:00:00-05:00",
    "lastRuntUpdateDate": "2025-05-02T18:12:30-05:00",
    "limitationOwnerships": [],
    "lineVehicle": "AX4 EVOLUTION",
    "ownerFullName": "JHAN CARLOS UTRIA ZAPATA",
    "ownerId": "cc1001912171",
    "placaVehicle": "AFL53G",
    "soatInsuranceRate": {
      "ADRES2": null,
      "CLASE DE VEHICULO": "",
      "CÓDIGO": "",
      "EDAD": null,
      "RUNT 3": null,
      "SUBTIPO": null,
      "SUBTOTAL": null,
      "TARIFA MAX. 1": null,
      "TOTAL A PAGAR": 0
    },
    "technicalData": {
      "capacitySeatedPassengers": "2",
      "grossVehicleWeight": null,
      "height": null,
      "length": null,
      "loadCapacity": null,
      "numberOfShafts": null,
      "numberOfTires": null,
      "weight": null,
      "width": null
    },
    "transitAuthority": "STRIA MCPAL TTOyTTE GALAPA",
    "transitLicense": "10031490332",
    "typeFuel": "GASOLINA",
    "typeService": "Particular",
    "typeVehicle": "MOTOCICLETA",
    "uid": "",
    "warranties": [],
    "yearVehicle": "2023"
  },
  {
    "id": "HXP334",
    "brandVehicle": "KIA",
    "cardBody": "SEDAN",
    "chassisNumber": "KNAFX411AE5860574",
    "cityRegistration": "STRIA DTAL TTO BARRANQUILLA",
    "clasificationModelState": "linked",
    "color": "BLANCO", 
    "departmentRegistration": null,
    "displacement": "1591",
    "engineNumber": "G4FGDH690462",
    "initialRegistrationDate": "2014-05-28T00:00:00-05:00",
    "lastRuntUpdateDate": "2025-05-04T08:15:23-05:00",
    "limitationOwnerships": [],
    "lineVehicle": "CERATO PRO EX",
    "linksWithAdmins": null,
    "mainWorkingCity": "Barranquilla",
    "mainWorkingCountry": "Colombia",
    "mainWorkingDepartment": "Atlántico",
    "ownerAdminPath":
        "vehicleAdmin/Colombia/cc/1129520417/linkedOwner/cc32751824",
    "ownerFullName": "HEIDIS ESTHER TORRES DIAZ",
    "ownerId": "cc32751824",
    "ownerRolePath": "owner/Colombia/cc/32751824",
    "placaVehicle": "HXP334",
    "rentalVehicle": null,
    "roadKit": null,
    "soatInsuranceRate": {
      "ADRES2": null,
      "CLASE DE VEHICULO": "",
      "CÓDIGO": "",
      "EDAD": null,
      "RUNT 3": null,
      "SUBTIPO": null,
      "SUBTOTAL": null,
      "TARIFA MAX. 1": null,
      "TOTAL A PAGAR": 0
    },
    "technicalData": {
      "capacitySeatedPassengers": "5",
      "grossVehicleWeight": "1720",
      "maximumPVBPerConfiguration": "1720",
      "numberOfShafts": "2"
    },
    "transitAuthority": "STRIA DTAL TTO BARRANQUILLA",
    "transitLicense": "10031328374",
    "typeFuel": "GASOLINA",
    "typeService": "Particular",
    "typeVehicle": "AUTOMOVIL",
    "uid": "",
    "warranties": [],
    "yearVehicle": "2014"
  },
  {
    "id": "KZT537",
    "affiliateCompanyAdminPath": null,
    "affiliateCompanyId": "1HlMorDDsNgOZ2ZPzdVg",
    "affiliateCompanyName": "Taxi Prado",
    "affiliateCompanyRolePath": "affiliateCompany/1HlMorDDsNgOZ2ZPzdVg",
    "brandVehicle": "SUZUKI",
    "cardBody": "SEDAN",
    "chassisNumber": "MBHZF63S0PG195874",
    "cityRegistration": "STRIA TTOyTTE MCPAL SABANETA",
    "clasificationModelState": "linked",
    "color": "PLATA",
    "countryRegistration": "Colombia",
    "createdAt": "2025-03-28T18:40:56-05:00",
    "currentAdminId": "users/Colombia/cc/72184925",
    "currentLinkAdminToVehicleModelId": null,
    "displacement": "1197",
    "engineNumber": "K12MP4311321",
    "initialRegistrationDate": "2022-06-03T00:00:00-05:00",
    "lastRuntUpdateDate": "2025-03-28T18:40:56-05:00",
    "limitationOwnerships": [],
    "lineVehicle": "SWIFT DZIRE MT",
    "mainWorkingCity": "Barranquilla",
    "mainWorkingCountry": "Colombia",
    "mainWorkingDepartment": "Atlántico",
    "ownerAdminPath":
        "vehicleAdmin/Colombia/cc/72184925/linkedOwner/cc32751824",
    "ownerFullName": "HEIDIS ESTHER TORRES DIAZ",
    "ownerId": "cc32751824",
    "ownerRolePath": "owner/Colombia/cc/32751824",
    "placaVehicle": "KZT537",
    "soatInsuranceRate": {"TOTAL A PAGAR": 0},
    "technicalData": {
      "capacitySeatedPassengers": "5",
      "grossVehicleWeight": "1315",
      "maximumPVBPerConfiguration": "1315",
      "numberOfShafts": "2"
    },
    "transitAuthority": "STRIA TTOyTTE MCPAL SABANETA",
    "transitLicense": "10031463754",
    "typeFuel": "GASOLINA",
    "typeService": "Particular",
    "typeVehicle": "AUTOMOVIL",
    "yearVehicle": "2023"
  },
  {
    "id": "QFM52C",
    "brandVehicle": "TVS",
    "cardBody": "SIN CARROCERIA",
    "chassisNumber": "MD625MF52C1E65989",
    "cityRegistration": "INSTITUTO DE TRÁNSITO DEL ATLANTICO/BARANOA",
    "clasificationModelState": "linked",
    "color": "NEGRO VERDE",
    "countryRegistration": "Colombia",
    "createdAt": "2025-04-23T17:20:14-05:00",
    "currentAdminId": "users/Colombia/cc/72182645",
    "displacement": "99",
    "engineNumber": "DF5DC1171769",
    "initialRegistrationDate": "2012-09-18T19:00:00-05:00",
    "lastRuntUpdateDate": "2025-04-23T17:20:13-05:00",
    "lineVehicle": "TVS STAR SPORT 100",
    "mainWorkingCity": "Barranquilla",
    "mainWorkingCountry": "Colombia",
    "mainWorkingDepartment": "Atlántico",
    "ownerAdminPath":
        "vehicleAdmin/Colombia/cc/72182645/linkedOwner/cc72141536",
    "ownerFullName": "GERMAN FRANCISCO VEGA ALVAREZ",
    "ownerId": "cc72141536",
    "ownerRolePath": "owner/Colombia/cc/72141536",
    "placaVehicle": "QFM52C",
    "soatInsuranceRate": {"TOTAL A PAGAR": 0},
    "technicalData": {"capacitySeatedPassengers": "2"},
    "transitAuthority": "INSTITUTO DE TRÁNSITO DEL ATLANTICO/BARANOA",
    "transitLicense": "10004210962",
    "typeFuel": "GASOLINA",
    "typeService": "Particular",
    "typeVehicle": "MOTOCICLETA",
    "yearVehicle": "2013"
  }
];
