// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwIdOF1SNCe7Gulhfqrd2t9fJGQYUGPmI',
    appId: '1:778457383096:web:4f42cd811f9ad5edfa744d',
    messagingSenderId: '778457383096',
    projectId: 'avanzzaplus-98e47',
    authDomain: 'avanzzaplus-98e47.firebaseapp.com',
    storageBucket: 'avanzzaplus-98e47.firebasestorage.app',
    measurementId: 'G-RJMFM1FXWL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoo6jdlBA7UOag2OVxKG8nQEvtJYcRd4s',
    appId: '1:778457383096:android:8c0f90e4e8a427b2fa744d',
    messagingSenderId: '778457383096',
    projectId: 'avanzzaplus-98e47',
    storageBucket: 'avanzzaplus-98e47.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIqhTkNH523rWjcVD3soWoUcPnSJu8xVQ',
    appId: '1:778457383096:ios:5bef3e741b60f286fa744d',
    messagingSenderId: '778457383096',
    projectId: 'avanzzaplus-98e47',
    storageBucket: 'avanzzaplus-98e47.firebasestorage.app',
    iosBundleId: 'com.example.avanzza',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIqhTkNH523rWjcVD3soWoUcPnSJu8xVQ',
    appId: '1:778457383096:ios:5bef3e741b60f286fa744d',
    messagingSenderId: '778457383096',
    projectId: 'avanzzaplus-98e47',
    storageBucket: 'avanzzaplus-98e47.firebasestorage.app',
    iosBundleId: 'com.example.avanzza',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwIdOF1SNCe7Gulhfqrd2t9fJGQYUGPmI',
    appId: '1:778457383096:web:ff3f48e6e85f53f8fa744d',
    messagingSenderId: '778457383096',
    projectId: 'avanzzaplus-98e47',
    authDomain: 'avanzzaplus-98e47.firebaseapp.com',
    storageBucket: 'avanzzaplus-98e47.firebasestorage.app',
    measurementId: 'G-PRFTQ14FTP',
  );
}
